jobDefinitionName: '' # [REQUIRED] Specify a name for the job definition to register.
type: container
parameters: {} # These parameters will be overwritten
containerProperties:
  image: ghcr.io/seisscoped/quakescope:latest
  jobRoleArn: '' # [REQUIRED] The Amazon Resource Name (ARN) of the IAM role that the container can assume for AWS permissions.
  executionRoleArn: '' # [REQUIRED] The Amazon Resource Name (ARN) of the IAM role that the Amazon ECS container agent and the Docker daemon can assume.
  command:
  - pick
  - "--db_uri"
  - Ref::db_uri
  - "--database"
  - Ref::database
  - "--stations"
  - Ref::stations
  - "--start"
  - Ref::start
  - "--end"
  - Ref::end
  - "--classifier"
  - "--debug"
  resourceRequirements: # The type and amount of resources to assign to a container.
  - value: '8'
    type: VCPU
  - value: '16384'
    type: MEMORY
  secrets: []
  networkConfiguration:
    assignPublicIp: ENABLED
  fargatePlatformConfiguration:
    platformVersion: LATEST
  runtimePlatform:
    operatingSystemFamily: LINUX
    cpuArchitecture: X86_64
timeout:
  attemptDurationSeconds: 86400
tags: {}
platformCapabilities:
- FARGATE
retryStrategy:
  attempts: 10
  evaluateOnExit:
    - action: "RETRY"
      onStatusReason: "Your Spot Task was interrupted."
    - action: "EXIT"
      onReason: "*"
