NETWORK_MAPPING = {
    "1A": "earthscope",
    "1B": "earthscope",
    "1C": "earthscope",
    "1D": "earthscope",
    "1E": "earthscope",
    "1F": "earthscope",
    "1G": "earthscope",
    "1K": "earthscope",
    "1L": "earthscope",
    "1M": "earthscope",
    "1P": "earthscope",
    "1Q": "earthscope",
    "1T": "earthscope",
    "1U": "earthscope",
    "1V": "earthscope",
    "2A": "earthscope",
    "2B": "earthscope",
    "2C": "earthscope",
    "2D": "earthscope",
    "2E": "earthscope",
    "2F": "earthscope",
    "2G": "earthscope",
    "2H": "earthscope",
    "2K": "earthscope",
    "2L": "earthscope",
    "2O": "earthscope",
    "2P": "earthscope",
    "2Q": "earthscope",
    "2U": "earthscope",
    "2V": "earthscope",
    "3A": "earthscope",
    "3B": "earthscope",
    "3C": "earthscope",
    "3D": "earthscope",
    "3E": "earthscope",
    "3F": "earthscope",
    "3H": "earthscope",
    "3J": "earthscope",
    "3K": "earthscope",
    "3L": "earthscope",
    "3U": "earthscope",
    "3Y": "earthscope",
    "4A": "earthscope",
    "4E": "earthscope",
    "4F": "earthscope",
    "4H": "earthscope",
    "4J": "earthscope",
    "4N": "earthscope",
    "4P": "earthscope",
    "4Q": "earthscope",
    "4S": "earthscope",
    "4T": "earthscope",
    "4Y": "earthscope",
    "5A": "earthscope",
    "5C": "earthscope",
    "5E": "earthscope",
    "5F": "earthscope",
    "5G": "earthscope",
    "5H": "earthscope",
    "5K": "earthscope",
    "5L": "earthscope",
    "5P": "earthscope",
    "5S": "earthscope",
    "5W": "earthscope",
    "6A": "earthscope",
    "6C": "earthscope",
    "6D": "earthscope",
    "6E": "earthscope",
    "6F": "earthscope",
    "6G": "earthscope",
    "6H": "earthscope",
    "6I": "earthscope",
    "6J": "earthscope",
    "6K": "earthscope",
    "6L": "earthscope",
    "6O": "earthscope",
    "6Q": "earthscope",
    "6R": "earthscope",
    "6W": "earthscope",
    "7A": "earthscope",
    "7B": "earthscope",
    "7C": "earthscope",
    "7D": "earthscope",
    "7E": "earthscope",
    "7F": "earthscope",
    "7G": "earthscope",
    "7I": "earthscope",
    "7J": "earthscope",
    "7K": "earthscope",
    "7O": "earthscope",
    "7Q": "earthscope",
    "7S": "earthscope",
    "7T": "earthscope",
    "8A": "earthscope",
    "8B": "earthscope",
    "8E": "earthscope",
    "8F": "earthscope",
    "8G": "earthscope",
    "8H": "earthscope",
    "8J": "earthscope",
    "8L": "earthscope",
    "8Q": "earthscope",
    "8S": "earthscope",
    "8U": "earthscope",
    "8W": "earthscope",
    "9A": "earthscope",
    "9B": "earthscope",
    "9C": "earthscope",
    "9D": "earthscope",
    "9F": "earthscope",
    "9G": "earthscope",
    "9H": "earthscope",
    "9K": "earthscope",
    "9L": "earthscope",
    "9M": "earthscope",
    "9P": "earthscope",
    "9R": "earthscope",
    "A2": "earthscope",
    "A7": "earthscope",
    "AB": "earthscope",
    "AC": "earthscope",
    "AD": "earthscope",
    "AE": "earthscope",
    "AF": "earthscope",
    "AG": "earthscope",
    "AI": "earthscope",
    "AK": "earthscope",
    "AM": "earthscope",
    "AO": "earthscope",
    "AP": "earthscope",
    "AR": "earthscope",
    "AS": "earthscope",
    "AT": "earthscope",
    "AU": "earthscope",
    "AV": "earthscope",
    "AX": "earthscope",
    "AY": "earthscope",
    "AZ": "earthscope",
    "B6": "earthscope",
    "BC": "earthscope",
    "BE": "earthscope",
    "BG": "ncedc",
    "BI": "earthscope",
    "BK": "ncedc",
    "BL": "earthscope",
    "BN": "earthscope",
    "BP": "ncedc",
    "BV": "earthscope",
    "BX": "earthscope",
    "C": "earthscope",
    "C0": "earthscope",
    "C1": "earthscope",
    "C8": "earthscope",
    "CA": "earthscope",
    "CB": "earthscope",
    "CC": "earthscope",
    "CD": "earthscope",
    "CH": "earthscope",
    "CI": "scedc",
    "CK": "earthscope",
    "CM": "earthscope",
    "CN": "earthscope",
    "CO": "earthscope",
    "CS": "earthscope",
    "CT": "earthscope",
    "CU": "earthscope",
    "CW": "earthscope",
    "CY": "earthscope",
    "CZ": "earthscope",
    "DE": "earthscope",
    "DK": "earthscope",
    "DR": "earthscope",
    "DU": "earthscope",
    "DW": "earthscope",
    "DT": "earthscope",
    "EC": "earthscope",
    "EI": "earthscope",
    "EN": "earthscope",
    "EO": "earthscope",
    "EP": "earthscope",
    "ER": "earthscope",
    "ET": "earthscope",
    "FA": "earthscope",
    "G": "earthscope",
    "GB": "earthscope",
    "GE": "earthscope",
    "GG": "earthscope",
    "GH": "earthscope",
    "GI": "earthscope",
    "GM": "earthscope",
    "GO": "earthscope",
    "GR": "earthscope",
    "GS": "earthscope",
    "GT": "earthscope",
    "GY": "earthscope",
    "H2": "earthscope",
    "HK": "earthscope",
    "HL": "earthscope",
    "HT": "earthscope",
    "HU": "earthscope",
    "HV": "earthscope",
    "HW": "earthscope",
    "I0": "earthscope",
    "IC": "earthscope",
    "IE": "earthscope",
    "II": "earthscope",
    "IM": "earthscope",
    "IN": "earthscope",
    "IO": "earthscope",
    "IP": "earthscope",
    "IU": "earthscope",
    "IW": "earthscope",
    "JM": "earthscope",
    "JP": "earthscope",
    "K5": "earthscope",
    "KC": "earthscope",
    "KG": "earthscope",
    "KN": "earthscope",
    "KO": "earthscope",
    "KP": "earthscope",
    "KR": "earthscope",
    "KS": "earthscope",
    "KW": "earthscope",
    "KY": "earthscope",
    "KZ": "earthscope",
    "LB": "earthscope",
    "LD": "earthscope",
    "LH": "earthscope",
    "LI": "earthscope",
    "LM": "earthscope",
    "LO": "earthscope",
    "LX": "earthscope",
    "M8": "earthscope",
    "MB": "earthscope",
    "MC": "earthscope",
    "MG": "earthscope",
    "MI": "earthscope",
    "MM": "earthscope",
    "MN": "earthscope",
    "MP": "earthscope",
    "MR": "earthscope",
    "MS": "earthscope",
    "MU": "earthscope",
    "MX": "earthscope",
    "MY": "earthscope",
    "MZ": "earthscope",
    "N4": "earthscope",
    "NA": "earthscope",
    "NB": "earthscope",
    "NC": "ncedc",
    "NE": "earthscope",
    "NI": "earthscope",
    "NJ": "earthscope",
    "NK": "earthscope",
    "NL": "earthscope",
    "NM": "earthscope",
    "NN": "earthscope",
    "NO": "earthscope",
    "NP": "earthscope",
    "NQ": "earthscope",
    "NR": "earthscope",
    "NU": "earthscope",
    "NV": "earthscope",
    "NW": "earthscope",
    "NX": "earthscope",
    "NY": "earthscope",
    # GeoNet, not EarthScope. Both serve NZ and EarthScope's copy is in
    # us-east-2 - same region as the fleet, so faster per byte - but it mirrors
    # only 29 stations where GeoNet carries the whole network, 423 on a single
    # 2019 day. Cross-region reads are the price of 14x the stations.
    "NZ": "geonet",
    "O2": "earthscope",
    "OC": "earthscope",
    "OE": "earthscope",
    "OH": "earthscope",
    "OI": "earthscope",
    "OK": "earthscope",
    "ON": "earthscope",
    "OO": "earthscope",
    "OQ": "earthscope",
    "OV": "earthscope",
    "OW": "earthscope",
    "OX": "earthscope",
    "OZ": "earthscope",
    "PA": "earthscope",
    "PB": "earthscope",
    "PE": "earthscope",
    "PG": "ncedc",
    "PI": "earthscope",
    "PL": "earthscope",
    "PM": "earthscope",
    "PN": "earthscope",
    "PO": "earthscope",
    "PP": "earthscope",
    "PQ": "earthscope",
    "PR": "earthscope",
    "PS": "earthscope",
    "PT": "earthscope",
    "PY": "earthscope",
    "QZ": "earthscope",
    "RB": "earthscope",
    "RC": "earthscope",
    "RE": "earthscope",
    "RI": "earthscope",
    "RM": "earthscope",
    "RO": "earthscope",
    "RS": "earthscope",
    "RV": "earthscope",
    "S1": "earthscope",
    "S8": "earthscope",
    "SB": "earthscope",
    "SC": "earthscope",
    "SE": "earthscope",
    "SF": "earthscope",
    "SH": "earthscope",
    "SL": "earthscope",
    "SN": "earthscope",
    "SP": "earthscope",
    "SR": "earthscope",
    "SS": "earthscope",
    "SV": "earthscope",
    "TA": "earthscope",
    "TC": "earthscope",
    "TD": "earthscope",
    "TF": "earthscope",
    "TJ": "earthscope",
    "TM": "earthscope",
    "TO": "earthscope",
    "TR": "earthscope",
    "TT": "earthscope",
    "TW": "earthscope",
    "TX": "earthscope",
    "TZ": "earthscope",
    "UF": "earthscope",
    "UI": "earthscope",
    "UK": "earthscope",
    "UL": "ncedc",
    "UM": "earthscope",
    "UO": "earthscope",
    "US": "earthscope",
    "UU": "earthscope",
    "UW": "earthscope",
    "VE": "earthscope",
    "VU": "earthscope",
    "WA": "earthscope",
    "WC": "earthscope",
    "WF": "earthscope",
    "WI": "earthscope",
    "WM": "earthscope",
    "WU": "earthscope",
    "WW": "earthscope",
    "WR": "ncedc",
    "WY": "earthscope",
    "X1": "earthscope",
    "X2": "earthscope",
    "X3": "earthscope",
    "X4": "earthscope",
    "X5": "earthscope",
    "X6": "earthscope",
    "X7": "earthscope",
    "X8": "earthscope",
    "X9": "earthscope",
    "XA": "earthscope",
    "XB": "earthscope",
    "XC": "earthscope",
    "XD": "earthscope",
    "XE": "earthscope",
    "XF": "earthscope",
    "XG": "earthscope",
    "XH": "earthscope",
    "XI": "earthscope",
    "XJ": "earthscope",
    "XK": "earthscope",
    "XL": "earthscope",
    "XM": "earthscope",
    "XN": "earthscope",
    "XO": "earthscope",
    "XP": "earthscope",
    "XQ": "earthscope",
    "XR": "earthscope",
    "XS": "earthscope",
    "XT": "earthscope",
    "XU": "earthscope",
    "XV": "earthscope",
    "XW": "earthscope",
    "XX": "earthscope",
    "XY": "earthscope",
    "XZ": "earthscope",
    "Y1": "earthscope",
    "Y2": "earthscope",
    "Y3": "earthscope",
    "Y4": "earthscope",
    "Y5": "earthscope",
    "Y6": "earthscope",
    "Y7": "earthscope",
    "Y8": "earthscope",
    "Y9": "earthscope",
    "YA": "earthscope",
    "YB": "earthscope",
    "YC": "earthscope",
    "YD": "earthscope",
    "YE": "earthscope",
    "YF": "earthscope",
    "YG": "earthscope",
    "YH": "earthscope",
    "YI": "earthscope",
    "YJ": "earthscope",
    "YK": "earthscope",
    "YL": "earthscope",
    "YM": "earthscope",
    "YN": "earthscope",
    "YO": "earthscope",
    "YP": "earthscope",
    "YQ": "earthscope",
    "YR": "earthscope",
    "YS": "earthscope",
    "YT": "earthscope",
    "YU": "earthscope",
    "YV": "earthscope",
    "YW": "earthscope",
    "YX": "earthscope",
    "YY": "earthscope",
    "YZ": "earthscope",
    "Z1": "earthscope",
    "Z2": "earthscope",
    "Z3": "earthscope",
    "Z4": "earthscope",
    "Z5": "earthscope",
    "Z6": "earthscope",
    "Z7": "earthscope",
    "Z8": "earthscope",
    "Z9": "earthscope",
    "ZA": "earthscope",
    "ZB": "earthscope",
    "ZC": "earthscope",
    "ZD": "earthscope",
    "ZE": "earthscope",
    "ZF": "earthscope",
    "ZG": "earthscope",
    "ZH": "earthscope",
    "ZI": "earthscope",
    "ZJ": "earthscope",
    "ZK": "earthscope",
    "ZL": "earthscope",
    "ZM": "earthscope",
    "ZN": "earthscope",
    "ZO": "earthscope",
    "ZP": "earthscope",
    "ZQ": "earthscope",
    "ZR": "earthscope",
    "ZS": "earthscope",
    "ZT": "earthscope",
    "ZU": "earthscope",
    "ZV": "earthscope",
    "ZW": "earthscope",
    "ZX": "earthscope",
    "ZY": "earthscope",
    "ZZ": "earthscope",
}


# ---------------------------------------------------------------- channels
#
# One channel code per station-location, chosen by a fixed order rather than by
# inspecting sampling rates at read time. SEED band codes carry a standard rate
# range, so the ordering is a property of the code and can be decided once here;
# reading it per station-day would cost a metadata lookup per station-day to
# rediscover a constant.
#
# The set is the one the 2025 study processed: EH, HH, BH, HN, EP, DP, EL, SL,
# SH, CN. Ordering is by |standard rate - 100 Hz|, because PhaseNet resamples to
# 100 Hz and a channel already near it needs the least resampling.
#
#   band  SEED range        typical    |d 100|
#   H     80-250 Hz         100            0
#   E     80-250 Hz         100            0
#   S     10-80 Hz           50           50
#   B     10-80 Hz           40           60
#   D     250-1000 Hz       250          150
#   C     250-1000 Hz       250          150
#
# **Except for accelerometers, which sort last regardless of rate.** Corrected
# 2026-09-02 by M. Denolle: an accelerometer should be picked only when the
# station has no seismometer at all. They do not clip on large events, but their
# SNR on the small ones that dominate a catalogue is poor, and a catalogue built
# from an accelerometer where a broadband was available loses exactly the events
# it exists to find. Rate proximity is a resampling convenience; instrument
# class is a property of the data, and it wins.
#
# The previous order put HN (100 Hz accelerometer) above SH (50) and BH (40) on
# |d 100| alone, and dismissed the conflict as affecting "10 of 24,111
# western-states stations". Measured across all five 2026 campaigns it is 139
# station-locations and 528,758 station-days - 0.47% - all of them HN chosen
# over an available BH (460,279 sd) or SH (68,479 sd). Small, and wrong.
#
# Remaining tie-breaks, unchanged: within a rate group, high-gain seismometer
# (H) > geophone (P) > low-gain (L). And BH (40 Hz) still outranks DP (250 Hz),
# which is debatable - downsampling 250 -> 100 is lossless for the picking band
# while upsampling 40 -> 100 is not, so DP is arguably better; |d 100| says
# otherwise and stations carrying both are rare.
# **Low-gain and short-period-geophone bands were dropped 2026-09-02** by
# M. Denolle: deep-learning phase pickers are trained on BH, HH and EH, so
# picking on a band no training set contains is not a marginal choice, it is
# out of distribution. `EP`, `EL` and `SL` are gone; a station offering nothing
# else is skipped rather than picked badly. Cost: 3,631 stations and 344,778
# station-days, 0.31% of the campaign. A further 379,633 station-days move to a
# band that is in the training set.
CHANNEL_PRIORITY = [
    # what the pickers are actually trained on, by rate proximity to 100 Hz
    "HH",   # 100 Hz, high-gain seismometer
    "EH",   # 100 Hz, high-gain short-period
    "SH",   #  50 Hz, high-gain short-period
    "BH",   #  40 Hz, high-gain broadband
    # nodal geophone. Kept, but note that only the 2014 deployment is in
    # miniSEED - the rest of EarthScope's nodal archive is still PH5 - so most
    # DP station-days are expected to miss rather than pick. 61% of planned DP
    # station-days start in 2014, which is consistent with that.
    "DP",   # 250 Hz, geophone (nodal)
    # accelerometers last: only when nothing above is offered. Whether a picker
    # trained on BH/HH/EH should be used on HN at all is an open question, and
    # it is 46% of the campaign - see 17_launch_conventions.md.
    "HN",   # 100 Hz, accelerometer
    "CN",   # 250-1000 Hz, accelerometer (SEED band C, corner >= 10 s).
            # 169 stations, 0.4%; shares HN's open question.
]

CHANNEL_PRIORITY_INDEX = {c: i for i, c in enumerate(CHANNEL_PRIORITY)}


def select_channel(available):
    """The one channel code to pick on, from those a station offers.

    `available` accepts either two-character band codes ("HH", "BH") or full
    SEED channel codes ("HHZ", "BHN"); the component is dropped and duplicates
    collapse. Both forms are in use: western_states.csv stores bands, while the
    2025 per-network lists in networks/*.zip store full codes. Accepting only
    bands made the full-code form select nothing, and a station with no selected
    channel is skipped - so an entire campaign built from those files would have
    been silently empty rather than failing loudly.

    Codes outside CHANNEL_PRIORITY are ignored - the 2025 study defined the set,
    and picking on an LH or VH channel at 1 Hz or below would not produce usable
    arrivals. Returns None when a station offers nothing pickable, which the
    caller should treat as "skip this station" rather than as an error.
    """
    bands = {str(x).strip()[:2] for x in available if str(x).strip()}
    ranked = sorted(
        (c for c in bands if c in CHANNEL_PRIORITY_INDEX),
        key=lambda c: CHANNEL_PRIORITY_INDEX[c],
    )
    return ranked[0] if ranked else None
